/**
 * Package: PACKAGE_NAME Generated by: Hoang.Son.NguyenPS
 * C:\Users\Hoang.Son.Nguyen\OneDrive\Public\DockerGit> docker tag son_docker_git
 * nhsvn/my_docker_git PS C:\Users\Hoang.Son.Nguyen\OneDrive\Public\DockerGit> docker push
 * nhsvn/my_docker_git Generated at: 19.12.2018 2018
 */
public class DockerGit {
    public static void main(String [ ] args) throws InterruptedException {
    for (int i = 0; i < 10; i++) {
      System.out.println(i+": ich bin ein Test von Son und nun mit Jenkins");
      Thread.sleep(1000);
    }
    }
}
