/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.12.2018 2018
 */
public class DockerGit {
    public static void main(String [ ] args) throws InterruptedException {
    for (int i = 0; i < 10; i++) {
      System.out.println(i+": halhalha");
      Thread.sleep(1000);
    }
    }
}
