/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.12.2018 2018
 */
public class DockerGit {
    public static void main(String [ ] args)
    {
    System.out.println("halhalha");
    }
}
